// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: unicast.proto

package unicast

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgType int32

const (
	MsgType_PlainTxtT MsgType = 0
	MsgType_ImageT    MsgType = 1
	MsgType_VoiceT    MsgType = 2
	MsgType_LocationT MsgType = 3
	MsgType_SyncGroup MsgType = 4
	MsgType_FileT     MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "PlainTxtT",
		1: "ImageT",
		2: "VoiceT",
		3: "LocationT",
		4: "SyncGroup",
		5: "FileT",
	}
	MsgType_value = map[string]int32{
		"PlainTxtT": 0,
		"ImageT":    1,
		"VoiceT":    2,
		"LocationT": 3,
		"SyncGroup": 4,
		"FileT":     5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_unicast_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_unicast_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{0}
}

type Voice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32  `protobuf:"varint,1,opt,name=Length,proto3" json:"Length,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Voice) Reset() {
	*x = Voice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voice) ProtoMessage() {}

func (x *Voice) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voice.ProtoReflect.Descriptor instead.
func (*Voice) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{0}
}

func (x *Voice) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Voice) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32  `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ChatMessage_PlainTxt
	//	*ChatMessage_Image
	//	*ChatMessage_Voice
	//	*ChatMessage_Location
	//	*ChatMessage_SyncGroupId
	//	*ChatMessage_File
	Payload isChatMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unicast_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unicast_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_unicast_proto_rawDescGZIP(), []int{3}
}

func (m *ChatMessage) GetPayload() isChatMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ChatMessage) GetPlainTxt() string {
	if x, ok := x.GetPayload().(*ChatMessage_PlainTxt); ok {
		return x.PlainTxt
	}
	return ""
}

func (x *ChatMessage) GetImage() []byte {
	if x, ok := x.GetPayload().(*ChatMessage_Image); ok {
		return x.Image
	}
	return nil
}

func (x *ChatMessage) GetVoice() *Voice {
	if x, ok := x.GetPayload().(*ChatMessage_Voice); ok {
		return x.Voice
	}
	return nil
}

func (x *ChatMessage) GetLocation() *Location {
	if x, ok := x.GetPayload().(*ChatMessage_Location); ok {
		return x.Location
	}
	return nil
}

func (x *ChatMessage) GetSyncGroupId() string {
	if x, ok := x.GetPayload().(*ChatMessage_SyncGroupId); ok {
		return x.SyncGroupId
	}
	return ""
}

func (x *ChatMessage) GetFile() *File {
	if x, ok := x.GetPayload().(*ChatMessage_File); ok {
		return x.File
	}
	return nil
}

type isChatMessage_Payload interface {
	isChatMessage_Payload()
}

type ChatMessage_PlainTxt struct {
	PlainTxt string `protobuf:"bytes,2,opt,name=PlainTxt,proto3,oneof"`
}

type ChatMessage_Image struct {
	Image []byte `protobuf:"bytes,3,opt,name=Image,proto3,oneof"`
}

type ChatMessage_Voice struct {
	Voice *Voice `protobuf:"bytes,4,opt,name=voice,proto3,oneof"`
}

type ChatMessage_Location struct {
	Location *Location `protobuf:"bytes,5,opt,name=location,proto3,oneof"`
}

type ChatMessage_SyncGroupId struct {
	SyncGroupId string `protobuf:"bytes,6,opt,name=SyncGroupId,proto3,oneof"`
}

type ChatMessage_File struct {
	File *File `protobuf:"bytes,7,opt,name=file,proto3,oneof"`
}

func (*ChatMessage_PlainTxt) isChatMessage_Payload() {}

func (*ChatMessage_Image) isChatMessage_Payload() {}

func (*ChatMessage_Voice) isChatMessage_Payload() {}

func (*ChatMessage_Location) isChatMessage_Payload() {}

func (*ChatMessage_SyncGroupId) isChatMessage_Payload() {}

func (*ChatMessage_File) isChatMessage_Payload() {}

var File_unicast_proto protoreflect.FileDescriptor

var file_unicast_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x33, 0x0a, 0x05, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x58, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x42,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0xd8, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x74,
	0x12, 0x16, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x05, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x59, 0x0a,
	0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x69,
	0x6e, 0x54, 0x78, 0x74, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x54, 0x10, 0x02, 0x12,
	0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x10, 0x05, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x68, 0x6f, 0x6d, 0x65,
	0x2f, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x5f, 0x6c, 0x69,
	0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x2f, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x73, 0x74, 0x3b, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_unicast_proto_rawDescOnce sync.Once
	file_unicast_proto_rawDescData = file_unicast_proto_rawDesc
)

func file_unicast_proto_rawDescGZIP() []byte {
	file_unicast_proto_rawDescOnce.Do(func() {
		file_unicast_proto_rawDescData = protoimpl.X.CompressGZIP(file_unicast_proto_rawDescData)
	})
	return file_unicast_proto_rawDescData
}

var file_unicast_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_unicast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_unicast_proto_goTypes = []interface{}{
	(MsgType)(0),        // 0: MsgType
	(*Voice)(nil),       // 1: Voice
	(*Location)(nil),    // 2: Location
	(*File)(nil),        // 3: File
	(*ChatMessage)(nil), // 4: ChatMessage
}
var file_unicast_proto_depIdxs = []int32{
	1, // 0: ChatMessage.voice:type_name -> Voice
	2, // 1: ChatMessage.location:type_name -> Location
	3, // 2: ChatMessage.file:type_name -> File
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_unicast_proto_init() }
func file_unicast_proto_init() {
	if File_unicast_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unicast_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unicast_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unicast_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unicast_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_unicast_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ChatMessage_PlainTxt)(nil),
		(*ChatMessage_Image)(nil),
		(*ChatMessage_Voice)(nil),
		(*ChatMessage_Location)(nil),
		(*ChatMessage_SyncGroupId)(nil),
		(*ChatMessage_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unicast_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unicast_proto_goTypes,
		DependencyIndexes: file_unicast_proto_depIdxs,
		EnumInfos:         file_unicast_proto_enumTypes,
		MessageInfos:      file_unicast_proto_msgTypes,
	}.Build()
	File_unicast_proto = out.File
	file_unicast_proto_rawDesc = nil
	file_unicast_proto_goTypes = nil
	file_unicast_proto_depIdxs = nil
}
