// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.12.3
// source: contact.proto

package contact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactMsgType int32

const (
	ContactMsgType_MTAddContact      ContactMsgType = 0
	ContactMsgType_MTUpdateContact   ContactMsgType = 1
	ContactMsgType_MTDeleteContact   ContactMsgType = 2
	ContactMsgType_MTAddBlackList    ContactMsgType = 3
	ContactMsgType_MTRemoveBlackList ContactMsgType = 4
	ContactMsgType_MTAck             ContactMsgType = 5
	ContactMsgType_MTQueryContact    ContactMsgType = 6
	ContactMsgType_MTContactList     ContactMsgType = 7
)

// Enum value maps for ContactMsgType.
var (
	ContactMsgType_name = map[int32]string{
		0: "MTAddContact",
		1: "MTUpdateContact",
		2: "MTDeleteContact",
		3: "MTAddBlackList",
		4: "MTRemoveBlackList",
		5: "MTAck",
		6: "MTQueryContact",
		7: "MTContactList",
	}
	ContactMsgType_value = map[string]int32{
		"MTAddContact":      0,
		"MTUpdateContact":   1,
		"MTDeleteContact":   2,
		"MTAddBlackList":    3,
		"MTRemoveBlackList": 4,
		"MTAck":             5,
		"MTQueryContact":    6,
		"MTContactList":     7,
	}
)

func (x ContactMsgType) Enum() *ContactMsgType {
	p := new(ContactMsgType)
	*p = x
	return p
}

func (x ContactMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_contact_proto_enumTypes[0].Descriptor()
}

func (ContactMsgType) Type() protoreflect.EnumType {
	return &file_contact_proto_enumTypes[0]
}

func (x ContactMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactMsgType.Descriptor instead.
func (ContactMsgType) EnumDescriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{0}
}

type ContactItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID      string `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Remarks  string `protobuf:"bytes,3,opt,name=Remarks,proto3" json:"Remarks,omitempty"`
}

func (x *ContactItem) Reset() {
	*x = ContactItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactItem) ProtoMessage() {}

func (x *ContactItem) ProtoReflect() protoreflect.Message {
	mi := &file_contact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactItem.ProtoReflect.Descriptor instead.
func (*ContactItem) Descriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{0}
}

func (x *ContactItem) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *ContactItem) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *ContactItem) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type OperateAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *OperateAck) Reset() {
	*x = OperateAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateAck) ProtoMessage() {}

func (x *OperateAck) ProtoReflect() protoreflect.Message {
	mi := &file_contact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateAck.ProtoReflect.Descriptor instead.
func (*OperateAck) Descriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{1}
}

func (x *OperateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperateAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ContactList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contacts []*ContactItem `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *ContactList) Reset() {
	*x = ContactList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contact_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactList) ProtoMessage() {}

func (x *ContactList) ProtoReflect() protoreflect.Message {
	mi := &file_contact_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactList.ProtoReflect.Descriptor instead.
func (*ContactList) Descriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{2}
}

func (x *ContactList) GetContacts() []*ContactItem {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type ContactMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig    []byte         `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	From   string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Typ    ContactMsgType `protobuf:"varint,3,opt,name=typ,proto3,enum=pbs.contact.ContactMsgType" json:"typ,omitempty"`
	SeqVer int64          `protobuf:"varint,12,opt,name=seqVer,proto3" json:"seqVer,omitempty"`
	// Types that are assignable to PayLoad:
	//	*ContactMsg_AddOrUpdate
	//	*ContactMsg_DelC
	//	*ContactMsg_Block
	//	*ContactMsg_UndoBlock
	//	*ContactMsg_OpAck
	//	*ContactMsg_Query
	//	*ContactMsg_QueryResult
	PayLoad isContactMsg_PayLoad `protobuf_oneof:"PayLoad"`
}

func (x *ContactMsg) Reset() {
	*x = ContactMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contact_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactMsg) ProtoMessage() {}

func (x *ContactMsg) ProtoReflect() protoreflect.Message {
	mi := &file_contact_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactMsg.ProtoReflect.Descriptor instead.
func (*ContactMsg) Descriptor() ([]byte, []int) {
	return file_contact_proto_rawDescGZIP(), []int{3}
}

func (x *ContactMsg) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *ContactMsg) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ContactMsg) GetTyp() ContactMsgType {
	if x != nil {
		return x.Typ
	}
	return ContactMsgType_MTAddContact
}

func (x *ContactMsg) GetSeqVer() int64 {
	if x != nil {
		return x.SeqVer
	}
	return 0
}

func (m *ContactMsg) GetPayLoad() isContactMsg_PayLoad {
	if m != nil {
		return m.PayLoad
	}
	return nil
}

func (x *ContactMsg) GetAddOrUpdate() *ContactItem {
	if x, ok := x.GetPayLoad().(*ContactMsg_AddOrUpdate); ok {
		return x.AddOrUpdate
	}
	return nil
}

func (x *ContactMsg) GetDelC() string {
	if x, ok := x.GetPayLoad().(*ContactMsg_DelC); ok {
		return x.DelC
	}
	return ""
}

func (x *ContactMsg) GetBlock() string {
	if x, ok := x.GetPayLoad().(*ContactMsg_Block); ok {
		return x.Block
	}
	return ""
}

func (x *ContactMsg) GetUndoBlock() string {
	if x, ok := x.GetPayLoad().(*ContactMsg_UndoBlock); ok {
		return x.UndoBlock
	}
	return ""
}

func (x *ContactMsg) GetOpAck() *OperateAck {
	if x, ok := x.GetPayLoad().(*ContactMsg_OpAck); ok {
		return x.OpAck
	}
	return nil
}

func (x *ContactMsg) GetQuery() string {
	if x, ok := x.GetPayLoad().(*ContactMsg_Query); ok {
		return x.Query
	}
	return ""
}

func (x *ContactMsg) GetQueryResult() *ContactList {
	if x, ok := x.GetPayLoad().(*ContactMsg_QueryResult); ok {
		return x.QueryResult
	}
	return nil
}

type isContactMsg_PayLoad interface {
	isContactMsg_PayLoad()
}

type ContactMsg_AddOrUpdate struct {
	AddOrUpdate *ContactItem `protobuf:"bytes,4,opt,name=addOrUpdate,proto3,oneof"`
}

type ContactMsg_DelC struct {
	DelC string `protobuf:"bytes,6,opt,name=delC,proto3,oneof"`
}

type ContactMsg_Block struct {
	Block string `protobuf:"bytes,7,opt,name=block,proto3,oneof"`
}

type ContactMsg_UndoBlock struct {
	UndoBlock string `protobuf:"bytes,8,opt,name=undoBlock,proto3,oneof"`
}

type ContactMsg_OpAck struct {
	OpAck *OperateAck `protobuf:"bytes,9,opt,name=opAck,proto3,oneof"`
}

type ContactMsg_Query struct {
	Query string `protobuf:"bytes,10,opt,name=query,proto3,oneof"`
}

type ContactMsg_QueryResult struct {
	QueryResult *ContactList `protobuf:"bytes,11,opt,name=queryResult,proto3,oneof"`
}

func (*ContactMsg_AddOrUpdate) isContactMsg_PayLoad() {}

func (*ContactMsg_DelC) isContactMsg_PayLoad() {}

func (*ContactMsg_Block) isContactMsg_PayLoad() {}

func (*ContactMsg_UndoBlock) isContactMsg_PayLoad() {}

func (*ContactMsg_OpAck) isContactMsg_PayLoad() {}

func (*ContactMsg_Query) isContactMsg_PayLoad() {}

func (*ContactMsg_QueryResult) isContactMsg_PayLoad() {}

var File_contact_proto protoreflect.FileDescriptor

var file_contact_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x70, 0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0x55, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x43,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x73, 0x22, 0x38, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x43, 0x0a,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x73, 0x22, 0x97, 0x03, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x73, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2d, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x56, 0x65, 0x72,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x56, 0x65, 0x72, 0x12, 0x3c,
	0x0a, 0x0b, 0x61, 0x64, 0x64, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52,
	0x0b, 0x61, 0x64, 0x64, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x04,
	0x64, 0x65, 0x6c, 0x43, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x64, 0x65,
	0x6c, 0x43, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x09, 0x75, 0x6e,
	0x64, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x75, 0x6e, 0x64, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x05, 0x6f, 0x70,
	0x41, 0x63, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x73, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x70, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x3c, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x4c, 0x6f, 0x61, 0x64, 0x2a, 0xa9, 0x01, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x0c, 0x4d, 0x54, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x54, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x54, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4d,
	0x54, 0x41, 0x64, 0x64, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x4d, 0x54, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x54, 0x41, 0x63, 0x6b, 0x10,
	0x05, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x54, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x54, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x07, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x68, 0x6f, 0x6d, 0x65,
	0x2f, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x73, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contact_proto_rawDescOnce sync.Once
	file_contact_proto_rawDescData = file_contact_proto_rawDesc
)

func file_contact_proto_rawDescGZIP() []byte {
	file_contact_proto_rawDescOnce.Do(func() {
		file_contact_proto_rawDescData = protoimpl.X.CompressGZIP(file_contact_proto_rawDescData)
	})
	return file_contact_proto_rawDescData
}

var file_contact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contact_proto_goTypes = []interface{}{
	(ContactMsgType)(0), // 0: pbs.contact.ContactMsgType
	(*ContactItem)(nil), // 1: pbs.contact.ContactItem
	(*OperateAck)(nil),  // 2: pbs.contact.OperateAck
	(*ContactList)(nil), // 3: pbs.contact.ContactList
	(*ContactMsg)(nil),  // 4: pbs.contact.ContactMsg
}
var file_contact_proto_depIdxs = []int32{
	1, // 0: pbs.contact.ContactList.contacts:type_name -> pbs.contact.ContactItem
	0, // 1: pbs.contact.ContactMsg.typ:type_name -> pbs.contact.ContactMsgType
	1, // 2: pbs.contact.ContactMsg.addOrUpdate:type_name -> pbs.contact.ContactItem
	2, // 3: pbs.contact.ContactMsg.opAck:type_name -> pbs.contact.OperateAck
	3, // 4: pbs.contact.ContactMsg.queryResult:type_name -> pbs.contact.ContactList
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_contact_proto_init() }
func file_contact_proto_init() {
	if File_contact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contact_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contact_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contact_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_contact_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ContactMsg_AddOrUpdate)(nil),
		(*ContactMsg_DelC)(nil),
		(*ContactMsg_Block)(nil),
		(*ContactMsg_UndoBlock)(nil),
		(*ContactMsg_OpAck)(nil),
		(*ContactMsg_Query)(nil),
		(*ContactMsg_QueryResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contact_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contact_proto_goTypes,
		DependencyIndexes: file_contact_proto_depIdxs,
		EnumInfos:         file_contact_proto_enumTypes,
		MessageInfos:      file_contact_proto_msgTypes,
	}.Build()
	File_contact_proto = out.File
	file_contact_proto_rawDesc = nil
	file_contact_proto_goTypes = nil
	file_contact_proto_depIdxs = nil
}
